### ISSUE TITLE
An ability to use API keys for authentication instead of login+password

### ISSUE THREAD

**Issue by pavel-odintsov** [MEDIGO/go-zendesk#45]
Hello, guys!

Thank you for your hard work on this library! It works really well! I managed to create automatic user and ticket creation in less than few hours!

Great job!

But I'm looking for options to improve security of my application and use API keys instead of login and password.

Do you have plans to implement this feature?

Thank you!

**Comment by eggman64** [comment]
Hello Pavel,

This is in our pipeline, but we unfortunately cannot prioritize it. We would encourage you to send us a pull request, if you decide to roll it yourself :)

Cheers!

**Comment by ssimono** [comment]
Hello again @pavel-odintsov 

You can actually already use an api token, as it uses internally the same technical workflow.
All you need to do is to replace append `/token` to the *ZENDESK_USERNAME* environment variable, and use your API token as the password.

See  [Zendesk API docs](https://developer.zendesk.com/rest_api/docs/core/introduction#api-token) for details about the API

**Comment by pavel-odintsov** [comment]
Wow! That's awesome! Thank you, guys! :)

**Comment by pavel-odintsov** [comment]
It works! Cool! Thanks!
