### ISSUE TITLE
List tickets support

### ISSUE THREAD

**Issue by jpds** [MEDIGO/go-zendesk#67]
I'd like to be able to list tickets and also search for tickets with metadata with this library:

- https://developer.zendesk.com/rest_api/docs/core/tickets#list-tickets

**Comment by jpds** [comment]
I have an initial implementation of the search functionality in: https://github.com/jpds/go-zendesk/commit/6a7287878e4534f78fe5c6edb835a80695ff6f46

However the test is failing with:

```
--- FAIL: TestTicketCRUD (5.41s)
    require.go:794: 
        	Error Trace:	ticket_test.go:39
        	Error:      	Received unexpected error:
        	            	GET https://domain.zendesk.com/api/v2/tickets/search.json?query=evacuation: 400 Unknown: Oops! Something went wrong when parsing the error response.
        	Test:       	TestTicketCRUD
```

But I'm able to run:

```
$ curl "https://domain.zendesk.com/api/v2/search.json" -G --data-urlencode "query=evacuation" -v -u "username:password"
```

...just fine.

**Comment by jpds** [comment]
This appears to be done in feeadd9858c88c72ee958ff4ad0c405961cc7781.

@eggman64 Can you please confirm?

**Comment by eggman64** [comment]
Yes! Could you open a Pull Request?

**Comment by edevil** [comment]
This is done, right?

**Comment by eggman64** [comment]
> This is done, right?

Not yet. We now support
https://developer.zendesk.com/rest_api/docs/support/tickets#list-tickets-by-external-id

as well as
```
GET /api/v2/organizations/{organization_id}/tickets.json
GET /api/v2/users/{user_id}/tickets/requested.json
```

But not -

https://developer.zendesk.com/rest_api/docs/support/tickets#list-tickets

**Comment by edevil** [comment]
Addressed in https://github.com/MEDIGO/go-zendesk/pull/80
