### ISSUE TITLE
All tests should perform clean-up

### ISSUE THREAD

**Issue by jpds** [MEDIGO/go-zendesk#68]
It's really hard to develop against this library with the sandbox environment as some of the tests leave artefacts behind which makes the next test run fail.

**Comment by eggman64** [comment]
I'm sure we could use the Delete methods in the library to remove artifacts!
Would appreciate a PR with these changes :)

**Comment by eggman64** [comment]
This should be resolved with commit
https://github.com/MEDIGO/go-zendesk/commit/3fa76e046b900397e67a5fd7f50a74d36d760cd8

Please re-open if you feel this is still blocking you
