### ISSUE TITLE
Where is the Requester field?

### ISSUE THREAD

**Issue by PepijnK** [MEDIGO/go-zendesk#74]
Through the cURL command I can specifiy a requester field, however I can't find it in the tickets API of the library.
curl https://<subdomain>.zendesk.com/api/v2/tickets.json \
  -d '{"ticket": {"type": "question", "requester": {"name": "Username", "email": "user@emailaddy.com"}, "subject": "My printer is still on fire!", "comment": { "body": "The smoke is colorful." }, "custom_fields": [{"id": 1236432112, "value": "1.2.3.4"}]}}' \
  -H "Content-Type: application/json" -v -u addy@emailaddy.com:{ZENDESK_PASSWORD} -X POST

**Comment by eggman64** [comment]
Hello!

You can use `requester_id` as per the definition [here](https://developer.zendesk.com/rest_api/docs/support/tickets#json-format).

* Create a requester using `CreateOrUpdateUser`
* Pass the in the `requester_id` field

Alternatively, we're happy to receive a Pull Request, if you've implemented this feature.

Cheers
