### ISSUE TITLE
Zendesk Sell API support ? ( Create Lead )

### ISSUE THREAD

**Issue by KwanJunWen** [MEDIGO/go-zendesk#85]
Should Zendesk Sell API be included in this client library ? Currently trying to implement Core Sell API to [Create Lead](https://developers.getbase.com/docs/rest/reference/leads) but can't find it in this library

**Comment by eggman64** [comment]
Unfortunately the package only supports the core Zendesk APIs here - https://developer.zendesk.com/rest_api/docs/zendesk-apis/resources
Feel free to add the sell APIs and send us a PR
