### ISSUE TITLE
Add support for making an Identity primary

### ISSUE THREAD

**Issue by Wundark** [MEDIGO/go-zendesk#88]
Could the following endpoint be added?

https://developer.zendesk.com/rest_api/docs/support/user_identities#make-identity-primary

`PUT /api/v2/users/{user_id}/identities/{id}/make_primary`

**Comment by eggman64** [comment]
Hi @Wundark,

We currently do not support primary identity. Not sure how soon this will be done. But you could try this

``` go
	// update user identity
	identity := UserIdentity{
		Primary: true,
	}

	_, err = client.UpdateIdentity(*user.ID, *found[0].ID, &identity)
```

**Comment by eggman64** [comment]
Not sure if the `UpdateIdentity` will work for this. But it's worth a try

**Comment by Wundark** [comment]
@eggman64 Thanks for the reply. Unfortunately, the Zendesk docs say this can't be done.

> Note: You can't change an identity's primary attribute with this endpoint. Use the Make Identity Primary endpoint instead.

**Comment by eggman64** [comment]
#89
